force-app/main/default/objects/Tokenizer__mdt/Tokenizer__mdt.object-meta.xml
<CustomObject>
    <label>Tokenizer</label>
    <pluralLabel>Tokenizers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tokenizer__mdt/fields/num_Position__c.field-meta.xml
<CustomField>
    <fullName>num_Position__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Position</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group1Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group1Field__c</fullName>
    <label>Group 1 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group2Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group2Field__c</fullName>
    <label>Group 2 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group3Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group3Field__c</fullName>
    <label>Group 3 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group4Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group4Field__c</fullName>
    <label>Group 4 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group5Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group5Field__c</fullName>
    <label>Group 5 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TokenizersSelector.cls
public with sharing class TokenizersSelector extends fflib_SObjectSelector {

    // PUBLIC

    public Schema.SObjectType getSObjectType() {
        return Tokenizer__mdt.SObjectType;
    }


    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Tokenizer__mdt.Id,
            Tokenizer__mdt.DeveloperName,
            Tokenizer__mdt.Label,
            Tokenizer__mdt.chk_IsActive__c,
            Tokenizer__mdt.num_Position__c,
            Tokenizer__mdt.txl_RegExp__c,
            Tokenizer__mdt.txt_Group1Field__c,
            Tokenizer__mdt.txt_Group2Field__c,
            Tokenizer__mdt.txt_Group3Field__c,
            Tokenizer__mdt.txt_Group4Field__c,
            Tokenizer__mdt.txt_Group5Field__c
        };
    }


    public List<Tokenizer__mdt> allActiveInOrder() {
        return (List<Tokenizer__mdt>) Database.query( newQueryFactory()
                                                                .setCondition('chk_IsActive__c = TRUE')
                                                                .setOrdering(Tokenizer__mdt.num_Position__c, fflib_QueryFactory.SortOrder.ASCENDING)
                                                                .toSOQL() );
    }
}