force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorMailReceiver_Test.cls
@IsTest
private class ErrorMailReceiver_Test {

    @IsTest
    private static void receive(){

        // Setup
        Messaging.InboundEmail mail = new Messaging.InboundEmail();
        mail.fromAddress ='info@salesforce.com';
        mail.subject = 'Ignored';
        mail.plainTextBody = 'MailBody';


        // Exercise
        new ErrorMailReceiver().handleInboundEmail(mail, new Messaging.InboundEnvelope());


        // Verify
        System.assertEquals(mail.plainTextBody , [SELECT txl_FullMailBody__c FROM AppError__c LIMIT 1].txl_FullMailBody__c);
    }
}