force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/lkp_License__c.field-meta.xml
<CustomField>
    <fullName>lkp_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>sfLma__License__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_Package__c.field-meta.xml
<CustomField>
    <fullName>lkp_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>sfLma__Package__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_PackageVersion__c.field-meta.xml
<CustomField>
    <fullName>lkp_PackageVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Version</label>
    <referenceTo>sfLma__Package_Version__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>txt_ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_Location__c.field-meta.xml
<CustomField>
    <fullName>txt_Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_Namespace__c.field-meta.xml
<CustomField>
    <fullName>txt_Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_OrgId__c.field-meta.xml
<CustomField>
    <fullName>txt_OrgId__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_UserId__c.field-meta.xml
<CustomField>
    <fullName>txt_UserId__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_VisualforcePage__c.field-meta.xml
<CustomField>
    <fullName>txt_VisualforcePage__c</fullName>
    <label>Visualforce Page</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParseAppErrors_Test.cls
@IsTest
private class ParseAppErrors_Test {
    
    private static LmaPackage lmaPackage;
    private static LmaVersion lmaVersion;
    private static LmaLicense lmaLicense;
    private static List<String> mails;


    @IsTest
    private static void triggerError(){

        // Setup
        setup();


        // Exercise
        insert new AppError__c(txl_FullMailBody__c = mails[0]);


        // Verify
        AppError__c e = query()[0];
        System.assertEquals('005500000024uNj' , e.txt_UserId__c );
        System.assertEquals('00Dd0000000dsbB' , e.txt_OrgId__c );
        System.assertEquals('ACME.MyClass', e.txt_Location__c);
        System.assertEquals('ACME', e.txt_Namespace__c);
        System.assertEquals('System.LimitException' , e.txt_ExceptionType__c);
        System.assertEquals('Apex CPU time limit exceeded' , e.txt_ExceptionMessage__c);
        System.assertEquals('MyClass' , e.txt_ApexClass__c);
        System.assertEquals(null, e.txt_VisualforcePage__c);
        System.assertEquals(lmaLicense.Id, e.lkp_License__c);
        System.assertEquals(lmaPackage.Id, e.lkp_Package__c);
        System.assertEquals(lmaVersion.Id, e.lkp_PackageVersion__c);
    }


    @IsTest
    private static void visualforceError(){

        // Setup
        setup();


        // Exercise
        insert new AppError__c(txl_FullMailBody__c = mails[1]);


        // Verify
        AppError__c e = query()[0];
        System.assertEquals('005500000024uNj' , e.txt_UserId__c );
        System.assertEquals('00Dd0000000dsbB' , e.txt_OrgId__c );
        System.assertEquals('ACME', e.txt_Namespace__c);
        System.assertEquals('System.NullPointerException' , e.txt_ExceptionType__c);
        System.assertEquals('Attempt to de-reference a null object' , e.txt_ExceptionMessage__c);
        System.assertEquals('ACME.MyController' , e.txt_ApexClass__c);
        System.assertEquals('myPage' , e.txt_VisualforcePage__c);
        System.assertEquals('ACME.MyController.createSelectOptions: line 143, column 1' , e.txt_Location__c);
        System.assertEquals(lmaLicense.Id, e.lkp_License__c);
        System.assertEquals(lmaPackage.Id, e.lkp_Package__c);
        System.assertEquals(lmaVersion.Id, e.lkp_PackageVersion__c);
    }


    private static void reparseOnChange(){

        // Setup
        setup();

        AppError__c e = new AppError__c(txl_FullMailBody__c = mails[0]);
        insert e;


        // Exercise
        e.txl_FullMailBody__c.replaceAll('MyClass', 'MyOtherClass');
        update e;

        
        // Verify
        System.assertEquals('MyOtherClass' , e.txt_ApexClass__c);
    }


    @IsTest
    private static void realWorldErrors() {

        // Setup
        setup();


        // Exercise
        List<AppError__c> errors = new List<AppError__c>();
        for(String mail : mails) {
            errors.add(new AppError__c(txl_FullMailBody__c = mail));
        }
        insert errors;


        // Verify
        for(AppError__c e : query()) {
            System.assert(isPopulated(e), ''+e);
        }
    }


    // HELPER

    private static void setup() {
        lmaPackage = new LmaPackage().ns('ACME');
        lmaVersion = new LmaVersion(lmaPackage);
        lmaLicense = new LmaLicense(lmaVersion).org('00Dd0000000dsbB');
        lmaLicense.persist();

        StaticResource resource = [SELECT Body FROM StaticResource WHERE Name = 'error_mails_txt'];
        mails = resource.Body.toString().split('&');
        System.assert(!mails.isEmpty());
    }


    private static List<AppError__c> query() {
        return [SELECT txt_UserId__c, txt_OrgId__c, txt_Namespace__c, txt_ExceptionType__c, txt_ExceptionMessage__c,
                        txt_ApexClass__c, txt_VisualforcePage__c, txt_Location__c, lkp_License__c, lkp_Package__c, lkp_PackageVersion__c
                FROM AppError__c];
    }


    private static Boolean isPopulated(AppError__c record) {
        return (record.txt_UserId__c != null
                            && record.txt_OrgId__c != null
                            && record.txt_Namespace__c != null
                            && record.txt_ApexClass__c != null
                            && record.txt_Location__c != null
                            && record.txt_ExceptionMessage__c != null
                            && record.txt_ExceptionType__c != null
                            && record.lkp_License__c != null
                            && record.lkp_Package__c != null
                            && record.lkp_PackageVersion__c != null);
    }
}