force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_Insights__c.field-meta.xml
<CustomField>
    <fullName>txl_Insights__c</fullName>
    <label>Insights (powered by OpenAI)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ISV Cockpit Settings</label>
</CustomObject>

force-app/main/default/objects/Settings__c/fields/txt_OpenAiApiKey__c.field-meta.xml
<CustomField>
    <fullName>txt_OpenAiApiKey__c</fullName>
    <label>OpenAI API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddErrorInsights_Test.cls
@IsTest
private class AddErrorInsights_Test {
    
    @IsTest
    private static void apiCalledAndResultsStored() {

        // Setup
        insert new Settings__c(txt_OpenAiApiKey__c = 'any');

        AppError__c e = (AppError__c) new AppError().email(
                                'Apex script unhandled exception by user/organization: 005500000024uNj/00D000000000001\n\n' +
                                'Failed to process batch for class \'Namespace.MyBatchOb\' for job id \'7073X00009N7cij\'\n\n' +
                                'caused by: System.NullPointerException: Attempt to de-reference a null object\n\n' + 
                                ' External entry point')
                            .persist();
        Test.startTest();
        
        new HttpMock()
                .post('/v1/completions', 
                        new OpenAiCompletions.Response()
                                .withChoice('Check the Power cord'), 200)
                .mock();


        // Exercise
        AddErrorInsights.execute(new List<Id>{ e.Id });
        Test.stopTest();

        
        // Verify
        e = [SELECT txl_Insights__c FROM AppError__c LIMIT 1];
        Assert.areEqual('Check the Power cord', e.txl_Insights__c);
    }
}