force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/lkp_License__c.field-meta.xml
<CustomField>
    <fullName>lkp_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>sfLma__License__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SetupRetryUnparseable.cls
public with sharing class SetupRetryUnparseable extends BatchSetupStep {

	// PUBLIC

	public override ApexPages.Message getStatus() {
		ApexPages.Message result = super.getStatus();

		if(result == null) {
			Integer unassigned = [SELECT Count() FROM AppError__c WHERE lkp_License__c = NULL];
			ApexPages.Severity severity = (unassigned > 0) ? ApexPages.Severity.WARNING : ApexPages.Severity.CONFIRM;
			String message = unassigned + ' AppErrors are not assigned. Reparse them?';
			result = new ApexPages.Message(severity, message);
		}

		return result;
	}


	public List<SObject> start(Database.BatchableContext ctx) {
		return [SELECT Id FROM AppError__c WHERE lkp_License__c = NULL];
	}


	public void execute(Database.BatchableContext ctx, List<AppError__c> errors) {
		ParseAppErrors.parseAlways = true;
        update errors;
	}


	public void finish(Database.BatchableContext ctx) { }
}