force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/lkp_License__c.field-meta.xml
<CustomField>
    <fullName>lkp_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>sfLma__License__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetupReparse.cls
public with sharing class SetupReparse extends BatchSetupStep {

    public Integer batchSize {
        get {
            if(batchSize == null) {
                batchSize =  1;
            }
            return batchSize;
        }
        set; 
    }

    public String filter {
        get {
            if(filter == null) {
                filter = 'lkp_License__c = NULL OR txt_ExceptionType__c = NULL';
            }
            return filter;
        }
        set; 
    }
    
    public Integer recordCount {
        get {
            try {
                recordCount = Database.countQuery('SELECT Count() FROM AppError__c WHERE ' + filter);
            }
            catch(Exception ex) {
                ApexPages.addMessages(ex);
            }

            return recordCount;
        }
        private set; 
    }

	
	// PUBLIC

	public override ApexPages.Message getStatus() {
		ApexPages.Message result = super.getStatus();

        if(result == null) {
			ApexPages.Severity severity = (recordCount > 0) ? ApexPages.Severity.WARNING : ApexPages.Severity.CONFIRM;
			result = new ApexPages.Message(severity, 'Reparse ' + recordCount + ' AppErrors now?');
		}

		return result;
	}


	public override Integer batchSize() {
		return batchSize;
	}


    public PageReference refresh() {
        return null;
    }


	public List<SObject> start(Database.BatchableContext ctx) {
		return Database.query('SELECT Id FROM AppError__c WHERE ' + String.escapeSingleQuotes(filter));
	}


	public void execute(Database.BatchableContext ctx, List<AppError__c> errors) {
		ParseAppErrors.parseAlways = true;
        update errors;
	}


	public void finish(Database.BatchableContext ctx) { }
}