force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ArchivedAppError__b/ArchivedAppError__b.object-meta.xml
<CustomObject>
    <label>Archived App Error</label>
    <pluralLabel>Archived App Errors</pluralLabel>
</CustomObject>

force-app/main/default/classes/ArchiveRecords_Test.cls
@IsTest
private class ArchiveRecords_Test {

    private static Account_t account;
    private static LmaPackage app;
    private static LmaVersion version;
    private static LmaLicense license;
    private static List<String> mails;
    static {
        setup();   
    }


    @IsTest
    private static void happyPath() {

        // Setup
        insert new List<AppError__c>{
            new AppError__c(txl_FullMailBody__c = mails[0]),
            new AppError__c(txl_FullMailBody__c = mails[1])
        };


        // Exercise
        Test.startTest();

        ArchiveRecords command = new ArchiveRecords(AppError__c.SObjectType, ArchivedAppError__b.SObjectType, '');
        command.execute();

        Test.stopTest();


        // Verify
        System.assertEquals(2, command.archived.size());
        System.assertEquals(2, command.deleted.size());
    }


    // HELPER

    private static void setup() {
        account = new Account_t();
        app = new LmaPackage().name('App A').ns('NSA');
        version = new LmaVersion(app).name('v1');
        license = new LmaLicense(account, version).org('00D000000000001');
        account.persist();

        StaticResource resource = [SELECT Body FROM StaticResource WHERE Name = 'error_mails_txt'];
        mails = resource.Body.toString().split('&');
        System.assert(!mails.isEmpty());
    }
}