force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txt_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>txt_ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_Namespace__c.field-meta.xml
<CustomField>
    <fullName>txt_Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_OrgId__c.field-meta.xml
<CustomField>
    <fullName>txt_OrgId__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_UserId__c.field-meta.xml
<CustomField>
    <fullName>txt_UserId__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchErrorFormat.cls
public class BatchErrorFormat extends ParseAppErrors.EmailFormat {

    public override String regex() {
        return '(005[A-Za-z0-9]{12})/(00D[A-Za-z0-9]{12})' +
                '[\\s\\S]+' +
                'class \'([^\\.]+)\\.([^\']+)\'' +
                '[\\s\\S]+' +
                'caused by: ([^:]+): (.+)';
    }


    public override void populateFields(Matcher match, AppError__c error) {
        error.txt_UserId__c = match.group(1);
        error.txt_OrgId__c = match.group(2);
        error.txt_Namespace__c = match.group(3);
        error.txt_ApexClass__c = match.group(4);
        error.txt_ExceptionType__c = match.group(5);
        error.txt_ExceptionMessage__c = match.group(6).abbreviate(255);
    }
}