force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SetupRetryUnparseable_Test.cls
@IsTest
private class SetupRetryUnparseable_Test {

    private static List<String> mails;

    private static void setup() {
        Account_t a = new Account_t();
        LmaPackage p = new LmaPackage().name('App A').ns('NSA');
        LmaVersion v = new LmaVersion(p).name('v1');
        new LmaLicense(a, v)
                .org('00D000000000001')
                .persist();

        StaticResource resource = [SELECT Body FROM StaticResource WHERE Name = 'error_mails_txt'];
        mails = resource.Body.toString().split('&');
    }


    @IsTest
    private static void run() {

        // Setup
        setup();
        
        insert new AppError__c(txl_FullMailBody__c = mails[5]);

        SetupRetryUnparseable step = new SetupRetryUnparseable();
        System.assertEquals(1, step.unassigned);


        // Exercise
        step.run();


        // Verify
        System.assertEquals(0, step.unassigned);
    }
}