force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/dtm_RecordedDate__c.field-meta.xml
<CustomField>
    <fullName>dtm_RecordedDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Recorded Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_Account__c.field-meta.xml
<CustomField>
    <fullName>lkp_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>ErrorEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_License__c.field-meta.xml
<CustomField>
    <fullName>lkp_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>sfLma__License__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_Package__c.field-meta.xml
<CustomField>
    <fullName>lkp_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>sfLma__Package__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/lkp_PackageVersion__c.field-meta.xml
<CustomField>
    <fullName>lkp_PackageVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Version</label>
    <referenceTo>sfLma__Package_Version__c</referenceTo>
    <relationshipLabel>App Errors</relationshipLabel>
    <relationshipName>CustomerErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>txt_ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_OrgId__c.field-meta.xml
<CustomField>
    <fullName>txt_OrgId__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_UserId__c.field-meta.xml
<CustomField>
    <fullName>txt_UserId__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_VisualforcePage__c.field-meta.xml
<CustomField>
    <fullName>txt_VisualforcePage__c</fullName>
    <label>Visualforce Page</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppError.cls
public class AppError extends DomainBuilder {

    public AppError() {
        this(new LmaLicense());
    }
    

    public AppError(LmaLicense l) {
        super(AppError__c.SObjectType);

        setParent(AppError__c.lkp_License__c, l);
        setParent(AppError__c.lkp_Package__c,l.version.lmaPackage);
        setParent(AppError__c.lkp_PackageVersion__c, l.version);
        setParent(AppError__c.lkp_Account__c, l.account);

        set(AppError__c.txt_UserId__c, new Random().id(User.SObjectType));
        set(AppError__c.txt_OrgId__c, l.record.get(sfLma__License__c.sfLma__Subscriber_Org_ID__c));
        set(AppError__c.txt_ExceptionType__c, (new Random().string()+'Exception').capitalize());
        set(AppError__c.txt_ApexClass__c, (new Random().string()+'.cls').capitalize());
        set(AppError__c.txt_VisualforcePage__c, (new Random().string()+'.page').capitalize());
        set(AppError__c.txl_FullMailBody__c, 'empty ');
    }

    public AppError exception(String value) {
        return (AppError) set(AppError__c.txt_ExceptionType__c, value);
    }

    public AppError clazz(String value) {
        return (AppError) set(AppError__c.txt_ApexClass__c, value);
    }

    public AppError page(String value) {
        return (AppError) set(AppError__c.txt_VisualforcePage__c, value);
    }

    public AppError ver(LmaVersion value) {
        setParent(AppError__c.lkp_PackageVersion__c, value);
        sfLma__Package_Version__c version = (sfLma__Package_Version__c) value.record;
        Date release = version.sfLma__Release_Date__c.addDays(new Random().integer(1, 250));
        set(AppError__c.dtm_RecordedDate__c, DateTime.newInstance(release.year(), release.month(), release.day()));
        return this;
    }
}