force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txt_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>txt_ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>txt_ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txt_Namespace__c.field-meta.xml
<CustomField>
    <fullName>txt_Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecompileErrorToken.cls
public with sharing class RecompileErrorToken extends ParseAppErrors.Token {

    public override String regex() {
        return 'Dependent class is invalid and needs recompilation.+\\n(?:Class )([^.]+)\\.([^ ]+) : ([^:]+)$';
    }


    public override void populateFields(Matcher match, AppError__c error) {
        error.txt_Namespace__c = match.group(1);
        error.txt_ApexClass__c = match.group(2);
        error.txt_ExceptionType__c = '_InvalidDependentClassNeedsRecompile';
        error.txt_ExceptionMessage__c = abbreviate(match.group(3), 255);
    }
}