force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/Tokenizer__mdt.object-meta.xml
<CustomObject>
    <label>Tokenizer</label>
    <pluralLabel>Tokenizers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group1Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group1Field__c</fullName>
    <label>Group 1 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group2Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group2Field__c</fullName>
    <label>Group 2 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group3Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group3Field__c</fullName>
    <label>Group 3 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group4Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group4Field__c</fullName>
    <label>Group 4 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tokenizer__mdt/fields/txt_Group5Field__c.field-meta.xml
<CustomField>
    <fullName>txt_Group5Field__c</fullName>
    <label>Group 5 Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Tokenizer.cls
public with sharing class Tokenizer {

    private static final DescribeSObjectResult DESCRIBE = AppError__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED);

    private Pattern regex;
    private List<SObjectField> fields = new List<SObjectField>();


    // CONSTRCUTOR

    public Tokenizer(Tokenizer__mdt record) {
        regex = Pattern.compile(record.txl_RegExp__c);
        
        for(String fieldValue : new List<String>{ record.txt_Group1Field__c, record.txt_Group2Field__c, record.txt_Group3Field__c, 
                                                  record.txt_Group4Field__c, record.txt_Group5Field__c}) {
            
            SObjectField field = (fieldValue != null) ? DESCRIBE.fields.getMap().get(fieldValue) : null;
            if(field != null) {
                fields.add(field);
            }
        }
    }


    // PUBLIC

    public void execute(AppError__c error) {
        Matcher match = regex.matcher( error.txl_FullMailBody__c );

        if(match.find()) {
            for(Integer index=0; index<fields.size(); index++) {
                SObjectField field = fields.get(index);
                String value = match.group(index + 1).abbreviate(field.getDescribe().getLength());
                
                error.put(field, value);
            }
        }
    }


    public static List<Tokenizer> initialize() {
        List<Tokenizer> result = new List<Tokenizer>();

        for(Tokenizer__mdt record : new TokenizersSelector().allActiveInOrder()) {
            result.add(new Tokenizer(record));
        }
        
        return result;
    }
}