force-app/main/default/objects/AppError__c/AppError__c.object-meta.xml
<CustomObject>
    <label>App Error</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>App Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppError__c/fields/txl_FullMailBody__c.field-meta.xml
<CustomField>
    <fullName>txl_FullMailBody__c</fullName>
    <label>Full Mail Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AppError__c/fields/txl_Hints__c.field-meta.xml
<CustomField>
    <fullName>txl_Hints__c</fullName>
    <label>Hints (powered by OpenAI)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ISV Cockpit Settings</label>
</CustomObject>

force-app/main/default/objects/Settings__c/fields/txt_OpenAiApiKey__c.field-meta.xml
<CustomField>
    <fullName>txt_OpenAiApiKey__c</fullName>
    <label>OpenAI API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddErrorInsights.cls
public with sharing class AddErrorInsights {

    // PUBLIC

    @InvocableMethod(label = 'Add Error Insights from OpenAI')
    public static void execute(List<Id> errorIds) {
        List<AppError__c> errors = [SELECT txl_FullMailBody__c FROM AppError__c 
                                    WHERE Id IN :errorIds WITH SYSTEM_MODE];

        for(AppError__c error : errors) {
            error.txl_Hints__c = execute(error);
        }

        update as system errors;
    }


    // PRIVATE

    private static String execute(AppError__c error) {
        HttpResponse result = null;

        try {
            result = new Http().send(openAiRequestFor(error));

            if(result.getStatusCode() != 200) {
                throw new ApplicationException('Error: ' + result.getStatus());
            }
        } 
        catch(Exception ex) {
            throw new ApplicationException('Error: ' + ex.getMessage());
        }

        return OpenAiCompletions.response(result.getBody()).choices[0].message.content;
    }


    private static HttpRequest openAiRequestFor(AppError__c error) {
        HttpRequest result = new HttpRequest();
        result.setEndpoint('https://api.openai.com/v1/chat/completions');
        result.setMethod('POST');
        result.setHeader('Content-Type', 'application/json');
        result.setHeader('Authorization', 'Bearer ' + openAiApiKey());
        result.setTimeout(120000);
        result.setBody( new OpenAiCompletions.Request()
                                .model('gpt-4')
                                .message(new OpenAiCompletions.Message()
                                                .role('system')
                                                .content('You are an experienced Salesforce Developer of a Managed Package.'))
                                .message(new OpenAiCompletions.Message()
                                                .role('user')
                                                .content('You received the following automated error email from one of my subscriber orgs. What does it mean? \n\n' + error.txl_FullMailBody__c))
                                .asJson() );
        return result;
    }


    private static String openAiApiKey() {
        Settings__c result = Settings__c.getOrgDefaults();
        
        if(result == null || result.txt_OpenAiApiKey__c == null ) {
            throw new ApplicationException('No OpenAI API Key found in Settings.');
        }

        return result.txt_OpenAiApiKey__c;
    }
}