force-app/main/default/objects/PackageUsageSummary__c/PackageUsageSummary__c.object-meta.xml
<CustomObject>
    <label>Package Usage Summary</label>
    <nameField>
        <displayFormat>PUS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Usage Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PackageUsageSummary__c/fields/ext_OrganizationId__c.field-meta.xml
<CustomField>
    <fullName>ext_OrganizationId__c</fullName>
    <label>Organization ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/ext_PackageId__c.field-meta.xml
<CustomField>
    <fullName>ext_PackageId__c</fullName>
    <label>Package ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/num_Creates__c.field-meta.xml
<CustomField>
    <fullName>num_Creates__c</fullName>
    <label>Num Creates</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/num_Deletes__c.field-meta.xml
<CustomField>
    <fullName>num_Deletes__c</fullName>
    <label>Num Deletes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/num_Reads__c.field-meta.xml
<CustomField>
    <fullName>num_Reads__c</fullName>
    <label>Num Reads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/num_Updates__c.field-meta.xml
<CustomField>
    <fullName>num_Updates__c</fullName>
    <label>Num Updates</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/num_Views__c.field-meta.xml
<CustomField>
    <fullName>num_Views__c</fullName>
    <label>Num Views</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_CustomEntity__c.field-meta.xml
<CustomField>
    <fullName>txt_CustomEntity__c</fullName>
    <label>Custom Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_CustomEntityType__c.field-meta.xml
<CustomField>
    <fullName>txt_CustomEntityType__c</fullName>
    <label>Custom Entity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_ManagedPackageNamespace__c.field-meta.xml
<CustomField>
    <fullName>txt_ManagedPackageNamespace__c</fullName>
    <label>Managed Package Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_Month__c.field-meta.xml
<CustomField>
    <fullName>txt_Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_UserIdToken__c.field-meta.xml
<CustomField>
    <fullName>txt_UserIdToken__c</fullName>
    <label>User ID Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackageUsageSummary__c/fields/txt_UserType__c.field-meta.xml
<CustomField>
    <fullName>txt_UserType__c</fullName>
    <label>User Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConvertAppAnalytics_Test.cls
@IsTest
private class ConvertAppAnalytics_Test {

    private static final String CSV = [SELECT Body FROM StaticResource WHERE Name = 'record_logs_csv'].Body.toString();

    @IsTest
    private static void execute() {

        // Setup
        // Note: Take the fake ids in the Static Resource CSV
        new LmaPackage().id('0333h000000HNlV')
            .add(new LmaVersion().id('04t1R000001MSgE'))
            .persist();
        

        // Exercise 
        new ConvertAppAnalytics(CSV).execute();


        // Verify
        List<PackageUsageSummary__c> summaries = [SELECT txt_CustomEntity__c, txt_CustomEntityType__c, txt_ManagedPackageNamespace__c, txt_Month__c,  
                                                        num_Creates__c, num_Deletes__c, num_Reads__c, num_Updates__c, num_Views__c, ext_OrganizationId__c, ext_PackageId__c, txt_UserIdToken__c, txt_UserType__c
                                                 FROM PackageUsageSummary__c];
        System.assert(!summaries.isEmpty());

        for(PackageUsageSummary__c record : summaries) {
            System.assert(String.isNotBlank(record.txt_CustomEntity__c), '' + record);
            System.assert(String.isNotBlank(record.txt_CustomEntityType__c), '' + record);
            System.assert(String.isNotBlank(record.txt_ManagedPackageNamespace__c), '' + record);
            System.assert(String.isNotBlank(record.txt_Month__c), '' + record);
            System.assertNotEquals(null, record.num_Creates__c);
            System.assertNotEquals(null, record.num_Deletes__c);
            System.assertNotEquals(null, record.num_Reads__c);
            System.assertNotEquals(null, record.num_Updates__c);
            System.assertNotEquals(null, record.num_Views__c);
            System.assert(String.isNotBlank(record.ext_OrganizationId__c), '' + record);
            System.assert(String.isNotBlank(record.ext_PackageId__c), '' + record);
            System.assert(String.isNotBlank(record.txt_UserIdToken__c), '' + record);
            System.assert(String.isNotBlank(record.txt_UserType__c), '' + record);
        }
    }


    @IsTest
    private static void parse() {

        // Exercise
        List<Map<String, String>> parsed = ConvertAppAnalytics.parse(CSV);


        // Verify
        System.assert(!parsed.isEmpty());
    }
}